### ISSUE TITLE
add unittest

### ISSUE THREAD

**Issue by sPyOpenSource** [sPyOpenSource/os#8]

**Comment by sPyOpenSource** [comment]
Null Test: 	Caused an ERROR
test.JUnitTest
java.lang.ClassNotFoundException: test.JUnitTest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)

**Comment by sPyOpenSource** [comment]
it is difficult to do that
